export const MetaData = {
  title:
    "Производство, изготовление и установка лестниц | Лестницы для дома. Доставка в Тюмени",
  description:
    "Продажа и производство, изготовление лестниц в Тюмени - под заказ по низким ценам. Доставка, монтаж, гарантия!",
};

export const accordeonItems = [
  {
    id: 1,
    name: "Виды лестниц",
    anchor: "top",
    value: [
      "⁃ <strong>Маршевые лестницы</strong> - удобные и практичные, идеально подходят для дома и офиса.",
      "⁃ <strong>Поворотные Г-образные лестницы</strong> - экономят пространство и придают интерьеру изысканность.",
      "⁃ <strong>П-образные лестницы</strong> - функциональные и стильные решения для больших помещений.",
      "⁃ <strong>Лестницы с площадкой</strong> - обеспечивают удобство и безопасность передвижения.",
      "⁃ <strong>Лестницы на швеллере</strong> - прочные и надежные конструкции, подходящие для различных помещений.",
      "⁃ <strong>Лестницы на косоуре</strong> - элегантные и современные, прекрасно вписываются в любой интерьер.",
      "⁃ <strong>Винтовые лестницы</strong> - компактные и эстетичные, идеально подходят для небольших помещений.",
      "⁃ <strong>Лестницы 'гусиный шаг'</strong> - эффективное решение для узких пространств и помещений с ограниченной высотой.",
    ],
  },
  {
    id: 2,
    name: "Места установки",
    anchor: "request",
    value: [
      "⁃ Дом",
      "⁃ Коттедж",
      "⁃ Квартира",
      "⁃ Улица",
      "⁃ Подвал",
      "⁃ Склад",
      "⁃ Магазин",
    ],
  },
  {
    id: 3,
    name: "Почему выбирают нас?",
    anchor: "price",
    value: [
      "<strong>Собственное производство</strong> металлоконструкций",
      "<strong>Бесплатный замер</strong> в удобное для Вас время",
      "<strong>Изготовление лестниц</strong> напрямую от производителя, благодаря чему стоимость ниже на 15-25%",
      "<strong>Индивидуальный подход</strong> - каждый проект разрабатывается с учетом ваших потребностей и предпочтений.",
      "<strong>Качество материалов</strong> - используем только проверенные и долговечные материалы.",
      "<strong>Профессионализм</strong> - наши мастера имеют большой опыт и высокую квалификацию.",
    ],
  },
];

export const reviews = [
  {
    id: 1,
    published: true,
    content: "content",
    text: "Прекрасно справились с установкой лестницы в нашем коттедже. Качество материалов и профессионализм на высшем уровне!",
    rating: 5,
    user: {
      work: "домохозяйка",
      image: "/images/avatar1.jpeg",
      lastName: "Иванова",
      firstName: "Дарья",
    },
  },
  {
    id: 2,
    published: true,
    content: "content",
    text: "Гипнотерапия оказалась для меня настоящим открытием. Сеансы помогли мне избавиться от давней зависимости, и теперь я чувствую себя свободным и полным сил.",
    rating: 5,
    user: {
      work: "предприниматель",
      image: "/images/avatar2.jpeg",
      lastName: "Иванов",
      firstName: "Максим",
    },
  },
  {
    id: 3,
    published: true,
    content: "content",
    text: "Системные расстановки помогли мне наладить отношения в семье и понять корни многих проблем. Настоящий профессионал своего дела, который помог увидеть и решить глубинные вопросы",
    rating: 5,
    user: {
      work: "домохозяйка",
      image: "/images/avatar3.jpeg",
      lastName: "Иванова",
      firstName: "Дарья",
    },
  },
  {
    id: 4,
    published: true,
    content: "content",
    text: "Семейная терапия с этим специалистом спасла наш брак. Мы научились лучше понимать друг друга и находить компромиссы, что сделало нашу жизнь намного гармоничнее.",
    rating: 5,
    user: {
      work: "домохозяйка",
      image: "/images/avatar4.jpeg",
      lastName: "Иванова",
      firstName: "Дарья",
    },
  },
  {
    id: 5,
    published: true,
    content: "content",
    text: "Мой ребенок стал гораздо спокойнее и счастливее после работы с этим психологом. Очень благодарна за помощь и внимательное отношение к ребенку, что дало ощутимые положительные результаты.",
    rating: 5,
    user: {
      work: "домохозяйка",
      image: "/images/avatar5.jpeg",
      lastName: "Иванова",
      firstName: "Дарья",
    },
  },
  {
    id: 6,
    published: true,
    content: "content",
    text: "Потрясающий специалист! Очень помог разобраться с моими тревогами и научил, как с ними справляться. Теперь я чувствую себя намного увереннее и спокойнее, что положительно сказывается на моей повседневной жизни",
    rating: 5,
    user: {
      work: "домохозяйка",
      image: "/images/avatar1.jpeg",
      lastName: "Иванова",
      firstName: "Дарья",
    },
  },
];

export const files = [
  {
    alt: "stairs",
    id: 1,
    name: "stairs",
    path: "/images/stairs1.JPG",
  },
  {
    alt: "stairs",
    id: 2,
    name: "stairs",
    path: "/images/stairs2.JPG",
  },
  {
    alt: "stairs",
    id: 3,
    name: "stairs",
    path: "/images/stairs3.JPG",
  },
  {
    alt: "stairs",
    id: 4,
    name: "stairs",
    path: "/images/stairs4.JPG",
  },
  {
    alt: "stairs",
    id: 5,
    name: "stairs",
    path: "/images/stairs5.JPG",
  },
  {
    alt: "stairs",
    id: 6,
    name: "stairs",
    path: "/images/stairs6.JPG",
  },
  {
    alt: "stairs",
    id: 7,
    name: "stairs",
    path: "/images/stairs7.JPG",
  },
  {
    alt: "stairs",
    id: 8,
    name: "stairs",
    path: "/images/stairs8.JPG",
  },
  {
    alt: "stairs",
    id: 9,
    name: "stairs",
    path: "/images/stairs9.JPG",
  },
  {
    alt: "stairs",
    id: 10,
    name: "stairs",
    path: "/images/stairs10.JPG",
  },
  {
    alt: "stairs",
    id: 11,
    name: "stairs",
    path: "/images/stairs11.JPG",
  },
  {
    alt: "stairs",
    id: 12,
    name: "stairs",
    path: "/images/stairs12.JPG",
  },
  {
    alt: "stairs",
    id: 13,
    name: "stairs",
    path: "/images/stairs13.jpeg",
  },
  {
    alt: "stairs",
    id: 14,
    name: "stairs",
    path: "/images/stairs14.jpeg",
  },
  {
    alt: "stairs",
    id: 15,
    name: "stairs",
    path: "/images/stairs15.jpeg",
  },
  {
    alt: "stairs",
    id: 16,
    name: "stairs",
    path: "/images/stairs16.jpeg",
  },
  {
    alt: "stairs",
    id: 17,
    name: "stairs",
    path: "/images/stairs17.jpeg",
  },
  {
    alt: "stairs",
    id: 18,
    name: "stairs",
    path: "/images/stairs18.jpeg",
  },
  {
    alt: "stairs",
    id: 19,
    name: "stairs",
    path: "/images/stairs19.jpeg",
  },
  {
    alt: "stairs",
    id: 20,
    name: "stairs",
    path: "/images/stairs20.jpeg",
  },
  {
    alt: "stairs",
    id: 21,
    name: "stairs",
    path: "/images/stairs21.jpeg",
  },
  {
    alt: "stairs",
    id: 22,
    name: "stairs",
    path: "/images/stairs22.jpeg",
  },
  {
    alt: "stairs",
    id: 23,
    name: "stairs",
    path: "/images/stairs23.jpeg",
  },
  {
    alt: "stairs",
    id: 24,
    name: "stairs",
    path: "/images/stairs24.jpeg",
  },
  {
    alt: "stairs",
    id: 25,
    name: "stairs",
    path: "/images/stairs25.jpeg",
  },
  {
    alt: "stairs",
    id: 26,
    name: "stairs",
    path: "/images/stairs26.jpeg",
  },
  {
    alt: "stairs",
    id: 27,
    name: "stairs",
    path: "/images/stairs27.jpeg",
  },
  {
    alt: "stairs",
    id: 28,
    name: "stairs",
    path: "/images/stairs28.jpeg",
  },
  {
    alt: "stairs",
    id: 29,
    name: "stairs",
    path: "/images/stairs29.jpeg",
  },
  {
    alt: "stairs",
    id: 30,
    name: "stairs",
    path: "/images/stairs30.jpeg",
  },
  {
    alt: "stairs",
    id: 31,
    name: "stairs",
    path: "/images/stairs31.jpeg",
  },
  {
    alt: "stairs",
    id: 32,
    name: "stairs",
    path: "/images/stairs32.jpeg",
  },
  {
    alt: "stairs",
    id: 33,
    name: "stairs",
    path: "/images/stairs33.jpeg",
  },
  {
    alt: "stairs",
    id: 34,
    name: "stairs",
    path: "/images/stairs34.jpeg",
  },
  {
    alt: "stairs",
    id: 35,
    name: "stairs",
    path: "/images/stairs35.jpeg",
  },
  {
    alt: "stairs",
    id: 36,
    name: "stairs",
    path: "/images/stairs36.jpeg",
  },
];
